# Generated by Django 3.2.6 on 2023-05-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.CharField(choices=[('1', 'Very Low'), ('2', 'Low'), ('3', 'Medium'), ('4', 'High'), ('5', 'Very High')], default='1', max_length=1),
        ),
    ]
