# Generated by Django 3.2.6 on 2023-05-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', '0003_user_cal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cal',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
